# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Control_Box_Panos
# label used for menu selection
label: Box Visibility and Control in PAN-OS
description: This procedure controls Box traffic through security policy rules in PAN-OS.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Box
    - Configure

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: source_zone
    description: Source Zone name
    default: any
    type_hint: text
  - name: destination_zone
    description: Destination Zone name
    default: any
    type_hint: text
  - name: sanction_action
    description: Allow Box base functionality (required for any additional Box function rules)?
    default: Allow
    type_hint: dropdown
    dd_list:
      - key: 'Allow'
        value: 'allow'
      - key: 'Deny'
        value: 'deny'
  - name: enterprise_action
    description: Allow access to the Entperise version of Box (Step 1.2.1)?
    default: Deny
    type_hint: dropdown
    dd_list:
      - key: 'Allow'
        value: 'allow'
      - key: 'Deny'
        value: 'deny'
  - name: consumer_action
    description: Allow access to the Consumer version of Box (Step 1.2.2)?
    default: Deny
    type_hint: dropdown
    dd_list:
      - key: 'Allow'
        value: 'allow'
      - key: 'Deny'
        value: 'deny'
  - name: upload_action
    description: Allow file uploads to Box (Step 1.3)?
    default: Deny
    type_hint: dropdown
    dd_list:
      - key: 'Allow'
        value: 'allow'
      - key: 'Deny'
        value: 'deny'
  - name: download_action
    description: Allow file downloads from Box (Step 1.4)?
    default: Deny
    type_hint: dropdown
    dd_list:
      - key: 'Allow'
        value: 'allow'
      - key: 'Deny'
        value: 'deny'
  - name: edit_action
    description: Allow renaming or creating files and folders in Dropbox (Step 1.5)?
    default: Deny
    type_hint: dropdown
    dd_list:
      - key: 'Allow'
        value: 'allow'
      - key: 'Deny'
        value: 'deny'
  - name: sharing_action
    description: Allow sharing through Dropbox (Step 1.6)?
    default: Deny
    type_hint: dropdown
    dd_list:
      - key: 'Allow'
        value: 'allow'
      - key: 'Deny'
        value: 'deny'
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: security_rules.xml
# ---------------------------------------------------------------------
# end of snippets section